In [20]:
import pandas as pd
import numpy as np

In [89]:
#necessary datasets


postcodes = pd.read_csv('postal_codes_data_final.csv')
postcode_array = postcodes['postcode'].to_numpy()

#create an array for the area in the right unit
area_m2 = postcodes['oppervlakte'].to_numpy()
area_km2 = area_m2 *10e-06

#create an array for the number of inhabitants and calculate population density
inhabitants = postcodes['aantal_inwoners'].to_numpy()
pop_density = inhabitants / area_km2

postcode_density = np.c_[postcode_array, pop_density]

#create postcode population density dictionary
pp_dict = dict(zip(postcode_array,pop_density))

In [94]:
stations = pd.read_csv('NS_stations_met_aangrenzende_postcodes.csv', delimiter = ',')
stations

#add the population density data for zone0
postcode_gebied_station_arr = stations['postcode_gebied_station'].to_numpy()

#create array with populetion density zone 0
pop_dens_zone0 = np.zeros(len(postcode_gebied_station_arr))
for i in range(len(postcode_gebied_station_arr)):
    pop_dens_zone0[i] = pp_dict[postcode_gebied_station_arr[i]]
    
#add to dataframe
stations['pop_density_zone0'] = pop_dens_zone0
stations


#calculate population density for zone1
zone1_arr = stations['postcode_aangrenzende_postcode_gebieden'].to_numpy()

#split strings into lists
for i in range(len(zone1_arr)):
    zone1_arr[i] = zone1_arr[i].split(',') 

#create array with population density for zone1
pop_dens_zone1 = np.zeros(len(zone1_arr))

#calculate average pop dens of postal codes
for j in range(len(zone1_arr)):
    sum_pop_dens = 0
    for i in range(len(zone1_arr[j])):    
        sum_pop_dens += pp_dict[int(zone1_arr[j][i])]
    avg_pop_dens = sum_pop_dens/len(zone1_arr[j])
    pop_dens_zone1[j] = avg_pop_dens

#add to dataframe
stations['pop_density_zone1'] = pop_dens_zone1
stations.to_csv('population_densities.csv')

,station_naam,postcode_gebied_station,postcode_aangrenzende_postcode_gebieden,pop_density_zone0,pop_density_zone1
123,Lage Zwalu,4926,"[4251, 4765, 4766, 4781, 4924, 4926, 4927]",17.890051,10.727434
89,Grou-Jirns,9001,"[9001, 8491, 8494, 8497, 9003, 9005, 9007, 900...",22.791266,11.477176
3,Akkrum,8491,"[9001, 8467, 8468, 8491, 8493, 8494, 8495, 9011]",28.227843,12.540703
13,Anna Paulo,1761,"[1756, 1757, 1759, 1761, 1764, 1766, 1774, 1778]",23.315072,13.851532
153,Olst,8121,"[7431, 8121, 8124, 8131, 8167, 8194, 8196]",20.307284,14.597766
...,...,...,...,...,...
182,Rotterdm C,3013,"[3011, 3012, 3013, 3014, 3021, 3032, 3033, 3039]",342.585939,1107.008436
142,Moerwijk,2524,"[2523, 2524, 2283, 2284, 2521, 2531, 2532]",1627.582233,1110.557376
143,Muiderprt,1093,"[1018, 1019, 1092, 1093, 1094, 1097, 1098]",1661.324656,1180.767382
183,Rotterdm N,3036,"[3034, 3035, 3036, 3037, 3051]",1570.857047,1214.130421
64,Dn Haag HS,2515,"[2512, 2515, 2511, 2516, 2521, 2525, 2526, 2595]",1503.291570,1264.350578